services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - app-network

  db:
    container_name: priorityhub-database
    image: postgres:15
    restart: always
    env_file:
      - ./priorityhub-backend/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

  backend:
    container_name: priorityhub-backend
    build: ./priorityhub-backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && npm run start:prod"
    env_file:
      - ./priorityhub-backend/.env
    networks:
      - app-network

  frontend:
    container_name: priorityhub-frontend
    build: ./priorityhub-frontend
    ports:
      - "3001:3001"
    env_file:
      - ./priorityhub-frontend/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
